---
  - hosts: web_servers
    gather_facts: false
    become: true

    vars_files:
      - web_vars.yml
      - "{{ env }}_vars.yml"
    handlers:
      - name: restart apache
        systemd:
          name: apache2
          state: restarted

    tasks:
      - name: Install php and apache2 web server
        apt:
          name: ['php', 'apache2']
          state: present
      - name: Install needed php extensions
        apt:
          name: "{{ php_extentions }}"
      - name: Check composer version
        shell:
          composer -V
        ignore_errors: true
        register: cur_composer_version
        changed_when: false
      - name: Download composer installer
        get_url:
          url: https://getcomposer.org/installer
          dest: /root/composer-setup.php
        when: cur_composer_version.rc != 0 or cur_composer_version.stdout.split(' ')[2] != composer_version
      - name: Install composer
        shell:
          php /root/composer-setup.php --install-dir /usr/local/bin --filename composer --version {{ composer_version }}
        when: cur_composer_version.rc != 0 or cur_composer_version.stdout.split(' ')[2] != composer_version
      - name: Run composer
        composer:
          working_dir: "{{ web_dir }}"
          command: install
      - name: Set apache dir variable if web directory is not part of web root and application name is defined
        set_fact:
          apache_dir: "{{ web_root }}/{{ app_name }}"
          create_link: true
        when: not web_dir.startswith(web_root) and app_name is defined
      - name: Set apache dir variable if web directory is part of web root
        set_fact:
          apache_dir: "{{ web_dir }}"
        when: web_dir.startswith(web_root)
      - name: create web directory symlink
        file:
          src: "{{ web_dir }}"
          dest: "{{ apache_dir }}"
          state: link
        when: create_link is defined
      - name: Create web directory
        file:
          name: "{{ apache_dir }}"
          state: directory
        when: create_link is not defined
      - name: Add new apache vhost
        template:
          src: templates/slim.conf.j2
          dest: /etc/apache2/sites-available/slim.conf
        notify: restart apache
      - name: Enable new apache vhost
        file:
          src: /etc/apache2/sites-available/slim.conf
          dest: /etc/apache2/sites-enabled/slim.conf
          state: link
        notify: restart apache
      - name: disable default apache vhost
        file:
          name: /etc/apache2/sites-enabled/000-default.conf
          state: absent
        notify: restart apache
      - include_tasks: "{{ env }}.yml"
